# Generated by Django 5.2.7 on 2025-12-01 04:56

import stdimage.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título do livro', max_length=250)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('cover_image', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='books/', variations={'optimized': {'crop': False, 'height': 560, 'width': 400}})),
                ('condition', models.CharField(choices=[('nw', 'Novo'), ('gd', 'Bom'), ('fr', 'Desgastado'), ('dm', 'Danificado')], help_text='Condição do livro', max_length=7)),
                ('status', models.CharField(choices=[('av', 'Disponível'), ('un', 'Indisponível'), ('rs', 'Reservado')], default='av', editable=False, max_length=12)),
                ('slug', models.SlugField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
