# Generated by Django 5.2.7 on 2025-10-21 11:55

import django.db.models.deletion
import stdimage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='Título do livro', max_length=200)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('cover_image', stdimage.models.StdImageField(force_min_size=False, upload_to='books/', variations={})),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Regular'), ('DAMAGED', 'Damaged')], help_text='Condição do livro', max_length=7)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('RESERVED', 'Reserved')], max_length=12)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('max_loan_period', models.PositiveIntegerField(default=14, help_text='Duração máxima do emprestimo em dias')),
                ('requires_deposit', models.BooleanField(default=True)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Valor cobrado para o empréstimo', max_digits=10, null=True)),
                ('allows_renewal', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=9)),
                ('custom_terms', models.TextField(help_text='Condições adicionais para o emprestimo')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_taken', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
