# Generated by Django 5.2.7 on 2025-10-21 12:20

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='books/', variations={}),
        ),
    ]
