# Generated by Django 5.2.7 on 2025-10-22 18:45

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=stdimage.models.StdImageField(blank=True, default='books/book_icon.png', force_min_size=False, null=True, upload_to='books/', variations={}),
        ),
    ]
