# Generated by Django 5.2.7 on 2025-10-22 19:29

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=stdimage.models.StdImageField(blank=True, default='image/book_icon.png', force_min_size=False, null=True, upload_to='books/', variations={'optimized': {'crop': False, 'height': 560, 'width': 400}}),
        ),
    ]
