# Generated by Django 5.2.7 on 2025-10-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_category_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category_books', to='books.category'),
        ),
    ]
