# Generated by Django 5.2.7 on 2025-10-26 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_remove_category_book_book_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='categories',
            new_name='category',
        ),
    ]
