# Generated by Django 5.2.7 on 2025-10-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_rename_categories_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='access_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='favorite_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='access_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='favorite_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
