# Generated by Django 5.2.7 on 2025-10-30 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_book_access_count_alter_book_favorite_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='access_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='favorite_count',
        ),
        migrations.RemoveField(
            model_name='category',
            name='access_count',
        ),
        migrations.RemoveField(
            model_name='category',
            name='favorite_count',
        ),
        migrations.AddField(
            model_name='book',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, editable=False, related_name='favorite_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='books_categories', to='books.category'),
        ),
    ]
