# Generated by Django 5.2.7 on 2025-10-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_remove_book_access_count_remove_book_favorite_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
