# Generated by Django 5.2.7 on 2025-11-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_book_is_visible'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
