# Generated by Django 5.2.7 on 2025-11-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_book_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='books_categories', to='books.category'),
        ),
    ]
