# Generated by Django 5.2.7 on 2025-11-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('nw', 'Novo'), ('gd', 'Bom'), ('fr', 'Desgastado'), ('dm', 'Danificado')], help_text='Condição do livro', max_length=7),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('av', 'Disponível'), ('un', 'Indisponível'), ('rs', 'Reservado')], max_length=12),
        ),
    ]
