# Generated by Django 5.2.7 on 2026-03-16 17:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_customuser_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=150)),
                ('complemento', models.CharField(blank=True, default='', max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('localidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('regiao', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telefone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_owner', to='usuarios.address'),
        ),
    ]
