# Generated by Django 5.2.7 on 2025-10-22 19:29

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_customuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=stdimage.models.StdImageField(blank=True, default='image/default_user.avif', force_min_size=False, null=True, upload_to='profiles', variations={'thumb': {'crop': True, 'height': 360, 'width': 360}}, verbose_name='Imagem'),
        ),
    ]
