# Generated by Django 5.2.7 on 2025-12-01 04:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('max_loan_period', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ap', 'Aprovado'), ('ac', 'Ativo'), ('or', 'Em Rota'), ('rt', 'Em Devolução'), ('cm', 'Completo'), ('cn', 'Cancelada'), ('ov', 'Atraso')], default='ap', max_length=9)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Valor cobrado para o empréstimo', max_digits=10, null=True)),
                ('allows_renewal', models.BooleanField(default=True)),
                ('custom_terms', models.TextField(blank=True, help_text='Condições adicionais para o emprestimo.', null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_loans', to='books.book')),
            ],
        ),
    ]
