# Generated by Django 5.2.7 on 2025-11-05 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0017_delete_loan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('max_loan_period', models.PositiveIntegerField(choices=[(7, '1 week'), (14, '2 weeks'), (21, '3 weeks'), (30, '1 month')], default=7)),
                ('requires_deposit', models.BooleanField(default=True)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Valor cobrado para o empréstimo', max_digits=10, null=True)),
                ('allows_renewal', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], default='ACTIVE', max_length=9)),
                ('custom_terms', models.TextField(blank=True, help_text='Condições adicionais para o emprestimo.', null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_loans', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_days', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pr', 'Submitted'), ('dn', 'Denied'), ('ap', 'Approved')], default='pr', max_length=2)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_orders', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
