# Generated by Django 5.2.7 on 2025-11-10 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0018_alter_book_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('max_loan_period', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ac', 'Active'), ('cm', 'Completed'), ('cn', 'Cancelled'), ('ov', 'Overdue')], default='ac', max_length=9)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Valor cobrado para o empréstimo', max_digits=10, null=True)),
                ('allows_renewal', models.BooleanField(default=True)),
                ('custom_terms', models.TextField(blank=True, help_text='Condições adicionais para o emprestimo.', null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_loans', to='books.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_borrower', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['ac', 'ov'])), fields=('book',), name='unique_active_loan_per_book_and_client')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_days', models.PositiveIntegerField(choices=[(7, '1 week'), (14, '2 weeks'), (21, '3 weeks'), (30, '1 month')], default=7)),
                ('status', models.CharField(choices=[('pr', 'Submitted'), ('ap', 'Approved'), ('dn', 'Denied')], default='pr', max_length=2)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_orders', to='books.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_borrower', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('borrower', 'book'), name='unique_order_per_user_and_book')],
            },
        ),
    ]
