# Generated by Django 5.2.7 on 2025-11-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loan',
            name='unique_active_loan_per_book_and_client',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_order_per_user_and_book',
        ),
    ]
