# Generated by Django 5.2.7 on 2025-11-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_remove_loan_unique_active_loan_per_book_and_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('ac', 'Active'), ('cm', 'Completed'), ('cn', 'Cancelled'), ('ov', 'Overdue')], default='ap', max_length=9),
        ),
    ]
