# Generated by Django 5.2.7 on 2025-11-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_order_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='allows_renewal',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='requires_deposit',
        ),
        migrations.AlterField(
            model_name='loan',
            name='max_loan_period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='required_days',
            field=models.PositiveIntegerField(choices=[(7, '1 week'), (14, '2 weeks'), (21, '3 weeks'), (30, '1 month')], default=7),
        ),
    ]
