# Generated by Django 5.2.7 on 2025-11-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_loan_allows_renewal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='allows_renewal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor cobrado para o empréstimo', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('ac', 'Active'), ('cm', 'Completed'), ('cn', 'Cancelled'), ('ov', 'Overdue')], default='ACTIVE', max_length=9),
        ),
    ]
