# Generated by Django 5.2.7 on 2025-11-28 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_alter_book_title'),
        ('loans', '0003_alter_loan_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ac', 'or', 'ov'])), fields=('book',), name='unique_active_loan_per_book'),
        ),
    ]
