# Generated by Django 5.2.7 on 2025-11-08 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_book_owner'),
        ('loans', '0004_loan_allows_renewal_loan_deposit_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ac')), fields=('user', 'book'), name='unique_active_loan_per_book_and_client'),
        ),
    ]
