# Generated by Django 5.2.7 on 2025-11-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loan_unique_active_loan_per_book'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loan',
            name='unique_active_loan_per_book',
        ),
    ]
