# Generated by Django 5.2.7 on 2025-11-08 22:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_book_owner'),
        ('loans', '0006_alter_loan_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loan',
            name='unique_active_loan_per_book_and_client',
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ac')), fields=('book',), name='unique_active_loan_per_book_and_client'),
        ),
    ]
