# Generated by Django 5.2.7 on 2025-11-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loan_unique_active_loan_per_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('ap', 'Aprovado'), ('ac', 'Ativo'), ('or', 'Em Rota'), ('rt', 'Em Devolução'), ('cm', 'Completo'), ('cn', 'Cancelada'), ('ov', 'Atraso')], default='ap', max_length=9),
        ),
    ]
