# Generated by Django 5.2.7 on 2025-11-09 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_book_owner'),
        ('loans', '0007_remove_loan_unique_active_loan_per_book_and_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pr', 'Submitted'), ('ap', 'Approved'), ('dn', 'Denied')], default='pr', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_order_per_user_and_book'),
        ),
    ]
