# Generated by Django 5.2.7 on 2025-11-09 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_book_owner'),
        ('loans', '0008_alter_order_unique_together_alter_order_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loan',
            name='unique_active_loan_per_book_and_client',
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ac', 'ov'])), fields=('book',), name='unique_active_loan_per_book_and_client'),
        ),
    ]
