# Generated by Django 5.2.7 on 2025-12-01 04:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_days', models.PositiveIntegerField(choices=[(7, '1 semana'), (14, '2 semanas'), (21, '3 semanas'), (30, '1 mês')], default=7)),
                ('status', models.CharField(choices=[('pr', 'Enviado'), ('ap', 'Aprovado'), ('cn', 'Cancelado'), ('dn', 'Negado')], default='pr', max_length=2)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_orders', to='books.book')),
            ],
        ),
    ]
